# Generated by Django 2.2.7 on 2019-11-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Open', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topping',
            field=models.CharField(default='', max_length=120),
        ),
    ]
