# Generated by Django 2.2.7 on 2019-11-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191122_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='chart',
        ),
    ]
