# Generated by Django 2.2.7 on 2019-11-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191122_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='chart',
            new_name='cart',
        ),
    ]
